### ISSUE TITLE
Problems decoding mp1 files with jo_mp1

### ISSUE THREAD

**Issue by deltabeard** [r-lyeh/FWK#1]
Hello.

I'm looking into using the jo_mp1 header from this repository to play mp1 audio files. I'm using the mp2enc program from the mjpegtool package to prepare my mp1 files with the command `mp2enc -b 64 -l 1 -o test.mp1 -r 44100 -m < test.wav`. I have an example wav and mp1 that I'm testing with attached.

I'm having an issue whereby jo_mp1 only decodes about half of the mp1 input file.

My source code is at https://github.com/deltabeard/mp12wav/blob/master/src/mp12wav.c I've tested my mp1 input file with ffmpeg, which converts to wav correctly.

Many thanks.

[test_files.zip](https://github.com/r-lyeh/FWK/files/5291654/test_files.zip)
* test_input.wav: original wav file
* test.mp1: file converted from wav to mp1 with mp2enc
* test_ffmpeg.wav: file converted from test.mp1 with ffmpeg
* test_jo_mp1.wav: file converted from test.mp1 with jo_mp1 header in this repo

**Comment by r-lyeh** [comment]
I  guess you are writing half of the required bytes when converting your data, as outputSize is the number of samples, but drwav expects number of bytes: fix your source by using `drwav_write_raw(&wav, outputSize * 2, output);`. that should make it afaik

**Comment by r-lyeh** [comment]
Also, if the problem persists, try to reach out original authors (David Reid for miniaudio; Jon Olick for jo_mp1) :D

**Comment by deltabeard** [comment]
> I guess you are writing half of the required bytes when converting your data, as outputSize is the number of samples, but drwav expects number of bytes: fix your source by using `drwav_write_raw(&wav, outputSize * 2, output);`. that should make it afaik

This was the exact issue. Thank you for the fix!

Great work as always.
