### ISSUE TITLE
Compile error clang/gcc

### ISSUE THREAD

**Issue by SushilRagoonath** [r-lyeh/FWK#10]
all tested on windows
Cannot compile gcc 9,2,0 with error message
C:\Users\Sushil\AppData\Local\Temp\ccmRZhxT.s: Assembler messages:
C:\Users\Sushil\AppData\Local\Temp\ccmRZhxT.s:546187: Error: incorrect register `%eax' used with `q' suffix
not sure how to get better error.

Cannot compile clang 12.0.0 with msvc(2022 preview)
fwk-f22eb2.o : error LNK2019: unresolved external symbol __udivti3 referenced in function mp_count_bits

I'm actually trying to build fwk as a dll so I create a better workflow but msvc wants __declspec so I'd rather try gcc/clang.
Also tcc is crashing after the cooking stage but I don't know how to debug it.

**Comment by r-lyeh** [comment]
1. gcc+win: compile with `-DLTC_NO_ASM` for now (debugged by compiling with -S, then inspecting the .s files manually).
2. clang+win: no idea, i'll have either to google or install your toolchain. what clang distro are you using?
3. msvc+dll: ah yes, i never thought i would have to support a fwk.dll build. i'll think about it.
4. tcc+win: damn broken again. tcc is a pita to support. i'll check that shortly
thanks for the feedback!

**Comment by SushilRagoonath** [comment]
Alright thanks, I think gcc symbol exporting is easier so I'll stick to that. I'll try reinstall the most standard clang setup and  update you on that.

**Comment by r-lyeh** [comment]
tcc+win: `tcc demo.c fwk.c -w -g -run` should make it for now... but there is something wrong for sure.

**Comment by r-lyeh** [comment]
clang+win: hint here https://github.com/ridiculousfish/libdivide/issues/56

**Comment by r-lyeh** [comment]
Moving this off to backlog
