### ISSUE TITLE
REQUESTS

### ISSUE THREAD

**Issue by r-lyeh** [r-lyeh/FWK#11]
Feel free to submit here all your feature requests & suggestions. Ideally, specify only a suggestion per written comment, rather than starting a whole chat/discussion in the thread.

- render: raster sprites in resolution independant way (@SushilRagoonath)
- render: helper function to debug/raster fbos in screen (by using either tile() or sprite(), with bool do_flipping option) (@SushilRagoonath)
- window: more flexibility when creating windows (since I dont want users to enter (w,h) resolution, maybe I should allow WINDOW_16_9, WINDOW_3_2, WINDOW_3_4, etc;) (@SushilRagoonath)
- render: maybe support for Vulkan, DirectX, and OpenGL ES? (@Rabios)
- platform: html5: consider going https://github.com/schellingb/wajic/issues/1 (@r-lyeh)

**Comment by r-lyeh** [comment]
@sushilragoonath commented : 
- raster sprites in resolution independant way,
- helper function to debug/raster fbos in screen (by using either tile() or sprite(), with bool do_flipping option)

**Comment by Rabios** [comment]
Maybe support for Vulkan, DirectX, and OpenGL ES helps?

**Comment by SushilRagoonath** [comment]
image/textures in debug ui. ui_image(...) maybe even ui_image_button.

**Comment by r-lyeh** [comment]
Moving this to Discussions.
