### ISSUE TITLE
Lovely project! I would like to run demo_luajit.lua on macOS

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#14]
On macOS 11.6.1, every other C demo runs fine, but running `luajit demo_luajit.lua` with LuaJIT 2.1.0-beta3 I get:

```shell
luajit: dlopen(libfwk.dylib, 5): Symbol not found: _glad_glEnable
  Referenced from: libfwk.dylib
  Expected in: flat namespace
 in libfwk.dylib
```

I built `libfwk.dylib` with the following commands:

```shell
cc -c -ObjC fwk.c -w -g $*
cc -dynamiclib -undefined suppress -flat_namespace *.o -o libfwk.dylib -framework cocoa -framework iokit -framework opengl
```

I looks like I need to install glad2 somehow. Checked on the homebrew side but found no available formula with that name.

Thank you for any help getting past this point and good luck with your awesome project!

**Comment by r-lyeh** [comment]
Hi @whoamigo 
I dont think anybody else have ever tried to run fwk on osx+luajit. I dont have access to an OSX machine, so we'll have to guess what's going wrong. I suspect the GLAD symbols in the .dylib library were not exported, or maybe trimmed. Can you try to add `-DGLAD_API_CALL_EXPORT` and see if it helps?

**Comment by whoamigo** [comment]
Thank you for the fast response @r-lyeh but `-DGLAD_API_CALL_EXPORT` didn't make any difference.

However, while checking the compilation output without the -w -g switches, I noticed that `glad` takes over many of the OpenGL symbol definitions. I haven't looked any deeper but is `glad` mandatory or do you have any means of calling OpenGL directly, thus avoiding 'glad'?

I'm anxious to see this working as I really love your project's goals :)

**Comment by r-lyeh** [comment]
Hmmm... Glad is not really mandatory on OSX as far as I know. I left it enabled because all demos worked and for consistency as well. I guess it could just work without glad at all. Ok, you could try to remove the glad headers in the `fwk` file maybe? Replace the whole Glad segment (lines 9-11776) with a single `#include <OpenGL/gl.h>` line. That should make it maybe. If it does, I'll rewrite the header

**Comment by r-lyeh** [comment]
Oh btw, silly me, you should compile the dynamic library with `-DAPI=EXPORT`. I forgot that part

**Comment by whoamigo** [comment]
@r-lyeh wait a minute :) I just noticed my build commands were also pulling demo.c inside the dylib and `-undefined suppress -flat_namespace` was hiding the problem until runtime. Let me check if I can write a cleaner build command first ;).

**Comment by r-lyeh** [comment]
Ok no hurries. If you use discord, we got a discord channel in https://discord.gg/hffwjfCJ
There is only one OSX user there, but I guess we could chat & help you if you join us there.

**Comment by whoamigo** [comment]
Meanwhile I think I have a better build command here:

`cc -ObjC -dynamiclib -o libfwk.dylib fwk.c -framework cocoa -framework iokit -framework opengl -DAPI=EXPORT`

which gives me less GL macro redefinitions but unfortunately crashes LuaJIT with a SIGSEGV (Address boundary error).

**Comment by whoamigo** [comment]
It gets  past:

```lua
local fwk=require('fwk')

print(fwk)

fwk.window_create(75.0,0) -- but crashes on window_create()
```

Do you have some easier function to test it such as fwk.version or alike :)

FFI bugs can be quite hard to understand.

**Comment by r-lyeh** [comment]
That command-line looks much better to me too.
Guess what, DLL+Win is crashing on latest code as well. I guess this broke sometime ago. Let me find what's going on :D

**Comment by r-lyeh** [comment]
Ok, I've pushed a fix for the crash. Let me know how that goes. You might need to invoke `git --reset hard HEAD~1 && git pull` to update to latest.

**Comment by whoamigo** [comment]
Awesome, that did it!

You may want to add this command to build the dylib on macOS:

`cc -ObjC -dynamiclib -o libfwk.dylib fwk.c -framework cocoa -framework iokit -framework opengl`

Not sure about the need to add the opengl framework however, but the more the merrier ;).

Keep up the good work! 👍

**Comment by r-lyeh** [comment]
Aye cool! I'll add the info to the readme! Ty!

**Comment by r-lyeh** [comment]
Btw, does it work if you remove the `-framework opengl` part? I don't think that's really needed as you said

**Comment by whoamigo** [comment]
@r-lyeh `-DAPI=EXPORT` is not needed and at least for demo_luajit.lua `-framework opengl` is not needed either.
