### ISSUE TITLE
Last commit gives errors when building dylib on macOS

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#17]
Hi @r-lyeh

Just a quick heads up regarding building as a dylib on macOS.

I am getting the usual warnings but the following errors are preventing the build:

```shell
fwk_obj.c:10:6: error: conflicting types for 'obj_free'
void obj_free( void *obj ) {
     ^
fwk_obj.h:53:17: note: previous declaration is here
API void        obj_free( const void *obj );
                ^
fwk_obj.c:17:6: error: conflicting types for 'obj_del'
void obj_del( void *obj ) {
     ^
fwk_obj.h:63:17: note: previous declaration is here
API void        obj_del( const void *obj );
                ^
fwk_obj.c:85:17: error: called object type 'int' is not a function or function pointer
    return MSIZE(ptr) - sizeof(void*);
           ~~~~~^
fwk_obj.c:176:7: error: conflicting types for 'obj_ref'
void* obj_ref(void *obj) {
      ^
fwk_obj.h:65:17: note: previous declaration is here
API void*       obj_ref( const void *obj );
                ^
fwk_obj.c:192:7: error: conflicting types for 'obj_unref'
void* obj_unref(void *obj) {
      ^
fwk_obj.h:66:17: note: previous declaration is here
API void*       obj_unref( const void *obj );
                ^
154 warnings and 5 errors generated.
```

Thanks

**Comment by r-lyeh** [comment]
Hey, @whoamigo , glad that you're testing this as I dont have access to OSX anymore :D
I've pushed a fix for the constness typos, they're not big deal. However, I cannot see what's wrong with the MSIZE(ptr) expression. Could you try to replace that with SYS_MSIZE(ptr) or xsize(ptr) and see if that works?

Btw, does the demo_instanced.c file run ok in OSX?
Thanks in advance!

**Comment by whoamigo** [comment]
OK, `SYS_MSIZE(ptr)` did it! I had to replace MSIZE(ptr) with SYS_MSIZE(ptr) in both fwk_obj.c (line 85) and fwk.c (line 15163).

demo_instanced.c also runs fine and it's really impressive!

May I ask you, as a favour, to add more "substance" to demo_luajit.lua than just displaying the window title? Maybe adding that little cute character :blush:.

**Comment by r-lyeh** [comment]
wait, are you compiling fwk_obj.c by any chance? that might explain why the MSIZE(ptr) call is failing there. you only need to compile fwk.c at root folder. fwk_obj.c, and any other file in art/source, is not meant to be compiled. they're there for browsing purposes.

regarding the lua demo, i'll try to port a more complex example in the future

**Comment by whoamigo** [comment]
@r-lyeh I haven't looked into the Makefile but for some reason both `cc -ObjC -dynamiclib -o libfwk.dylib fwk.c -framework cocoa -framework iokit` and `sh MAKE.bat dll` are also triggering a compilation of fwk_obj.c

**Comment by whoamigo** [comment]
Oh, wait. I assumed this line in the error log

```shell
fwk_obj.c:85:17: error: called object type 'int' is not a function or function pointer
    return MSIZE(ptr) - sizeof(void*);
```

meant that fwk_obj.c was compiled but in fact since fwk.c is an "amalgamation" of all the source files it's that part in fwk.c that is triggering the error.

So it's only in fwk.c (line 15163) that MSIZE(ptr) needs to be replaced with SYS_MSIZE(ptr) on macOS.

**Comment by whoamigo** [comment]
Just checked again and it's indeed only in fwk.c (line 15163) that MSIZE(ptr) needs to be replaced with SYS_MSIZE(ptr) on macOS. Otherwise the build fails with this error message:
```shell
fwk_obj.c:85:17: error: called object type 'int' is not a function or function pointer
    return MSIZE(ptr) - sizeof(void*);
           ~~~~~^
154 warnings and 1 error generated.
```

be it with `cc -ObjC -dynamiclib -o libfwk.dylib fwk.c -framework cocoa -framework iokit` or `sh MAKE.bat dll`

**Comment by r-lyeh** [comment]
> May I ask you, as a favour, to add more "substance" to demo_luajit.lua than just displaying the window title? Maybe adding that little cute character from demo_instanced.c 😊.

Added a little 3d demo in `demos/lua/demo_luajit_model.lua`. Just be sure to run it from root folder, so it can find either the art/ folder or the cooked .zipfiles.

![image](https://user-images.githubusercontent.com/35402248/156941359-6e57d582-c937-47fb-a51b-1a4593335a4c.png)
