### ISSUE TITLE
Thank you for the LuaJIT model demo

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#19]
Hi @r-lyeh,

The demo runs and is very low on CPU and memory.

The model seems to load:
```shell
000.107s|Loading VFS (kgirl/)kgirls01.fbx
```
I do see a new tiny grid in the middle. However, I can't see the character and I don't know how to zoom in. I tried the usual keyboard keys to navigate in the viewport like in Maya or Blender without success. I can only rotate around the "world" axis when I move the cursor. BTW, I do not have a mouse and I'm doing this with the trackpad.

Any idea on how I can navigate in the viewport and especially how can I zoom in to check if the character is there.

That's all really awesome. Thanks!

**Comment by r-lyeh** [comment]
Press the left or right mouse button anywhere within the game window, hold the mouse button, and then press the WASD E/C keys to move the first person camera. 
Also, your demo is not finding the game assets I guess. Notice if there is a `(not found)` line after that line you pasted. Something like this:
```
000.274s|Loading VFS (kgirl/)kgirls01.fbx                                                      |vfs_load|fwk_file.c:427
000.275s|Loading kgirl/kgirls01.fbx (not found)                                                |vfs_load|fwk_file.c:446
```
In that case...
- You need to copy the .art[*].zip files into the demos/lua folder.
- Or copy the art/ folder into demos/lua.
- Or copy the demos/lua/* files into / and run the demos from there.

**Comment by whoamigo** [comment]
That did it! Thank you @r-lyeh. I hadn't noticed those .art[*].zip files because they are normally hidden on macOS.

I now have this cute character boxing and kicking as should and the WASD E/C keys are also working fine.

I just can't believe how simple you made it to run such an animation as compared to other frameworks. You did an awesome job on FWK :sparkles:. Congratulations!
