### ISSUE TITLE
CPU usage on demo_luajit.lua has slightly increased

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#23]
Not by much but where it used to be `Steady at 9.7% CPU`, it is now more around 15%.

I thought you'd like to know it.

**Comment by r-lyeh** [comment]
oh, i cant think of any recent change that might slowdown the performance at the moment. 
could you identify the breaking commit please?

1. Run `git reset --hard HEAD^1 && sh MAKE.bat` 
2. Evaluate performance
3. If performance is not yet ok, goto step 1

That should give us some hints about which commit broke perf.

**Comment by whoamigo** [comment]
Lunch time :) I'll do this in the afternoon and keep you posted!

**Comment by r-lyeh** [comment]
Yeah no hurries, thanks for the report! I'll be aware of your progresses

**Comment by whoamigo** [comment]
I almost gave up, then did it the other way round starting at commit 623d27d6 (the one where the dylib started building) by checking out the commits. Here's the result of the percentage at which the CPU settles, without activity, when the `demo_luajit.lua` window is in front-most position on the Desktop:

Hash %CPU
623d27d6  9.7%
ba31a436  9.4%
a2dec04b  9.4%
ba31a436  9.9%
9007199b  9.3%
79cc52e4  11.7%
a97e8be3  12.2% (last commit)

Last commit settles at 12.2%. Sorry for reporting 15%.

**Comment by r-lyeh** [comment]
I suspect it could be either of these two blocks in the fwk.h header, or it could be both of them actually.
I cannot profile significantly enough on my computers. Could you try to reuse these old snippets and see if that increases perf on your computer?

```C
#define ALLOCSIZE(p)   xsize(p)
#define REALLOC(p,n)   (len1_ = (n), (len1_ ? WATCH(xrealloc((p),len1_),len1_) : xrealloc(FORGET(p),0)))
#define MALLOC(n)      REALLOC(0,(n))
#define FREE(p)        REALLOC(FORGET(p), 0)
#define CALLOC(m,n)    (len2_ = (m)*(n), memset(REALLOC(0,len2_),0,len2_))
#define STRDUP(s)      (len3_ = strlen(s)+1, ((char*)memcpy(REALLOC(0,len3_), (s), len3_)))
static __thread size_t len1_, len2_, len3_;
```

```C
#define each_substring(str, delims, keyname) \
    ( int len_ = strlen(str) + 1; len_; len_ = 0 ) \
    for( char buf_[1024], *ptr_ = len_ < 1024 ? buf_ : REALLOC(0, len_), *lit_ = (char*)(str), *_bak = (snprintf(ptr_, len_, "%s", lit_), ptr_); _bak; _bak = 0, (ptr_ == buf_ ? 0 : REALLOC(ptr_, 0)) ) \
    for( char *next_token = 0, *keyname = strtok_r(_bak, delims, &next_token); keyname; keyname = strtok_r(NULL, delims, &next_token) )
```

**Comment by whoamigo** [comment]
Wow! I simply replaced the appropriate section with the first block and CPU usage dropped. It is now oscillating between 9.2-10.1%. How can memory allocation influence CPU usage?

**Comment by r-lyeh** [comment]
I have no idea, the change introduced was slighty similar. 
I'll think about it until I figure out what made that impact.
For now, I cant revert simply the changes just because they were stability/potential crash fixes that we need to leave in.

For future me: this is the changed block 
https://github.com/r-lyeh/FWK/commit/79cc52e4c39f67bdebc189e84c442c63a5a4ec6d/fwk.h#diff-eff45383af7bb23477206af412a1c2466004ef006fbe69f89beb1500922b2afeL1675

PS: Did you manage to measure whether the second block is actually improving any %cpu as well?

**Comment by whoamigo** [comment]
The second block was already there.

**Comment by r-lyeh** [comment]
Ah yup, sorry for lack of instructions. Edit fwk.h:2488 and change that `#if 0` to `#if 1` to enable the old `each_substring` block
I'm curious to know if that is impacting performance as well on your computer.

**Comment by r-lyeh** [comment]
I've pushed a candidate fix in 8e2915d , I think that could help on your perf.
but I'd like to hear your opinions on the `each_substring` block as well!

**Comment by whoamigo** [comment]
I'm getting similar results. Maybe slightly higher.

**Comment by whoamigo** [comment]
BTW, I was checking some technical articles about modern CPU architecture and they seem to indicate that low memory does affect CPU performance.

**Comment by r-lyeh** [comment]
> I've pushed a candidate fix in [8e2915d](https://github.com/r-lyeh/FWK/commit/8e2915d3d4e78e8548438d0d156a7a063af43329) , I think that could help on your perf. but I'd like to hear your opinions on the `each_substring` block as well!

Whats the perf on that commit @whoamigo?

**Comment by whoamigo** [comment]
For some reason, I have not been notified that the issue was reopened.

With the current commit 25f5d76 the CPU usage is in the range of 8.8-10.2% while at commit 8e2915d it was in the range of 9.2-10.1%.

**Comment by r-lyeh** [comment]
No probs. Not quite sure if your issue is fixed completely by now though. Feel free either to close the issue for now or to keep it open to track it down in the future :D

**Comment by whoamigo** [comment]
The CPU usage is **very low** given the graphical nature of the application. I only wanted to understand the slight increase I had noticed and it's back to the first observation level. We can just as well close it now. If I were to notice any increase I'll let you know. Thanks

**Comment by r-lyeh** [comment]
well, thanks to you!
