### ISSUE TITLE
warn: material[3] not found in demo_scene

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#24]
Hi @r-lyeh,

It's not a biggie but the texture of the cute fighting character is missing.

```shell
000.797s|Loading VFS (demos/art/models/kgirl/)g01_texture.png (cached)file.c:543
000.798s|warn: material[3] not found: 01 - Default+g01_texture.png_render.c:3499
000.798s|warn: using placeholder material[3]=texture_checkeres|fwk_render.c:3500
```

**Comment by r-lyeh** [comment]
Good call. That should be fixed. I had introduced the issue recently meanwhile fixing the emscripten/html5 filesystem.

**Comment by whoamigo** [comment]
I can confirm that the texture is back. I must admit that I like that cute character :)
