### ISSUE TITLE
Expression failed: memory 3rd_nuklear.h in luajit demo_luajit.lua

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#27]
Now I'm getting this in luajit demo_luajit.lua:

```shell
000.195s|Expression failed: memory 3rd_nuklear.h:17451reakpoint|fwk_system.c:778

001: 0x0000000f810fd5 breakpoint
002: 0x0000000f82ec93 nk_font_atlas_add_from_memory
003: 0x0000000fa14cdc nk_config_custom_fonts
004: 0x0000000f967aec fwk_post_init
005: 0x0000000f967927 window_create_from_handle
006: 0x0000000f95fff3 window_create
007: 0x0000010f66b905 main
008: 0x0000010f6b7cb3 luaL_openlibs
'luajit demo_luajit.lua' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by r-lyeh** [comment]
it's weird that demo_luajit_model works for you and simple demo_luajit does not. the former is a way more complex demo.

**Comment by whoamigo** [comment]
Sorry to not have been clear on this. I get the same crash on both luajit demos.

**Comment by r-lyeh** [comment]
ah ok. how are you running the lua demos? ie, what is your commandline?
also, from which folder are you running the lua demos?
i just tested that on osx and it works for me. maybe it is an issue related to the current working directory.

**Comment by whoamigo** [comment]
Wait a minute @r-lyeh :) I was still copying manually the .zip files generated in the root folder. I removed them and found out they are generated when I run the demo and it's working!

**Comment by r-lyeh** [comment]
alrite then. yeah, you're not supposed to copy the files over anymore. 
but in any case, i'll keep an eye on that eventually. 
i think those .zip files should be compatible to a greater degree, and something else is broken.
