### ISSUE TITLE
Can I reflog the commits?

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#28]
@r-lyeh I'm not sure you're squashing your commits but is there any means I can follow the minute changes between two successive "commits"?

**Comment by r-lyeh** [comment]
yeah i know i should stop squeezing the git history, but i do a lot of small tests that i dont really want to publish. maybe i should work just in another branch, but i'm a old guy and i dont quite get the hang of that workflow. 

`git reset --hard HEAD^1 && git pull` should make it, in any case :D

**Comment by whoamigo** [comment]
No problem and I'm quite sure I'm almost twice your age ;)
