### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by RandyGaul** [r-lyeh/FWK#4]
What's your plan, and did you want any help with collaboration?

**Comment by r-lyeh** [comment]
hey randy. I ported this gist from vurtun into AVA (hence, its math code is already compatible with FWK) sometime ago: https://gist.github.com/vurtun/95f088e4889da2474ad1ce82d7911fee

I was planning to use directly this to see how it behaves (I could merge that into FWK over the weekend).
I know you've done c2/qu3e in the past, so I am open to suggestions and ideas :D

**Comment by RandyGaul** [comment]
Ah yes his GJK implementation was actually based off of one I created a while ago, so I can attest it's good quality. Should be great place to start with. I always like working on/chatting about collision detection so feel free to hit me up if you work on it more and wanted more eyes!

**Comment by r-lyeh** [comment]
I already submitted a compilable version of it. I have yet to create some visual tests to ensure nothing got broken since I originally ported it
