### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [r-lyeh/FWK#5]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/113958379-94bc2d80-9853-11eb-87ae-4d0879a2c135.png)

thank you  
best regards to you  
William

**Comment by r-lyeh** [comment]
hey william,
what is the linux version you are using? also, what is the libassimp version that you are using?
meanwhile we fix the issue, might you try this fork in the meantime and see if it works for you?

https://github.com/procedural/FWK_08_Apr_2021

**Comment by r-lyeh** [comment]
also, does it work after you install wine on your system?

**Comment by r-lyeh** [comment]
so william, it seems that @procedural kinda fixed the whole issue with his latest commit in his fork.
i have merged it back into this repository.
you could get latest with `git reset --hard HEAD~1 && git pull` and give it a try ?

**Comment by r-lyeh** [comment]
Do not hesitate to reopen this ticket if the issue persists
